name: Build
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  relay:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -f relay.Dockerfile -t ghcr.io/andyleap/nostr/relay:${{ github.sha }} .
      - name: Login
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push
        run: |
          docker push ghcr.io/andyleap/nostr/relay:${{ github.sha }}
